Add ConfigureServices
Stupid-Fox/CoffeeHouse pull request #11
Opened 2022-07-13 08:28 UTC by Stupid-Fox

2022-07-13 08:41 UTC, stas1408123 requested changes

2022-07-13 08:41 UTC, stas1408123 commented on CoffeeHouse.Api/Controllers/CoffeeController.cs
> +            services.AddTransient<ICoffeeService, CoffeeService>();
Add folder Di in BLL 
Implement extension method AddBLLDependencies()

2022-07-13 08:41 UTC, stas1408123 commented on CoffeeHouse.BLL/Services/CoffeeService.cs
> +            services.AddTransient<ICoffeeRepository, CoffeeRepository>();
Add folder Di in DAL 
Implement extension method AddDALDependencies()

2022-07-13 09:16 UTC, hromau approved these changes

2022-07-13 09:16 UTC, hromau approved these changes

2022-07-13 11:10 UTC, stas1408123 requested changes

2022-07-13 11:10 UTC, stas1408123 commented on CoffeeHouse.Api/Program.cs
> +builder.Services.AddSingleton<ICoffeeService, CoffeeService>();
Remove

2022-07-13 11:10 UTC, stas1408123 commented on CoffeeHouse.DAL/Di/Di.cs
> +            services.AddTransient<ICoffeeRepository, CoffeeRepository>();
Add database dependencies

2022-07-14 08:07 UTC, stas1408123 commented
Read comments in my past review

2022-07-14 10:37 UTC, hromau approved these changes

2022-07-15 07:32 UTC, stas1408123 approved these changes

2022-07-15 07:32 UTC, stas1408123 commented on CoffeeHouse.DAL/Di/Di.cs
> +        public static IServiceCollection AddDatabase(this IServiceCollection services, IConfiguration configuration)
Return void

2022-07-15 07:32 UTC, stas1408123 commented on CoffeeHouse.DAL/Di/Di.cs
> +            services.AddDbContext<CoffeeContext>(options => options.UseSqlServer(connection));
services.AddDbContext<CoffeeContext>(options => options.UseSqlServer(configuration.GetConnectionString("DefaultConnection")));

2022-07-15 07:32 UTC, stas1408123 commented on CoffeeHouse.BLL/Services/CoffeeService.cs
> +            services.AddDALDependencies(config);
WTF?

2022-07-15 07:32 UTC, stas1408123 commented on CoffeeHouse.BLL/Di/Di.cs
> +            services.AddTransient<ICoffeeService, CoffeeService>();
Add DAL Dependecy

2022-07-15 07:52 UTC, closed without merging