Bd Creating and Controller Update
Stupid-Fox/CoffeeHouse pull request #6
Opened 2022-07-06 10:47 UTC by Stupid-Fox

2022-07-06 10:50 UTC, stas1408123 requested changes

2022-07-06 10:50 UTC, stas1408123 commented on CoffeeHouse.Api/Controllers/CoffeeController.cs
> +        public async Task<ActionResult<IEnumerable<Coffee>>> Put(Coffee request)
Check method update

2022-07-06 11:36 UTC, hromau requested changes

2022-07-06 11:36 UTC, hromau commented on CoffeeHouse.Api/Controllers/CoffeeController.cs
> +        public async Task<ActionResult<IEnumerable<Coffee>>> GetAll()
delete all async, make ur code sync. get rid action result

2022-07-06 11:36 UTC, hromau commented on CoffeeHouse.Api/Controllers/CoffeeController.cs
> +            return Ok(await _context.Coffees.ToListAsync());
u must have to return object or objects, not Ok

2022-07-06 11:36 UTC, hromau commented on CoffeeHouse.Api/Models/Coffee.cs
> +
?

2022-07-06 11:36 UTC, hromau commented on CoffeeHouse.Api/Models/CoffeeContext.cs
> +
?

2022-07-06 11:36 UTC, hromau commented on CoffeeHouse.Api/Program.cs
> +
what the spaces?

2022-07-06 11:36 UTC, hromau commented on CoffeeHouse.Api/Program.cs
> +// �������� ������ ����������� �� ����� ������������
ïîëó÷àåì ñòðîêó ïîäêëþ÷åíèÿ èç ôàéëà êîíôèãóðàöèè

2022-07-06 11:36 UTC, hromau commented on CoffeeHouse.Api/Program.cs
> +// ��������� �������� ApplicationContext � �������� ������� � ����������
äîáàâëÿåì êîíòåêñò ApplicationContext â êà÷åñòâå ñåðâèñà â ïðèëîæåíèå

2022-07-06 11:36 UTC, hromau commented on CoffeeHouse.Api/Program.cs
> +// ��������� �������� ApplicationContext � �������� ������� � ����������
äîáàâëÿåì êîíòåêñò ApplicationContext â êà÷åñòâå ñåðâèñà â ïðèëîæåíèå

2022-07-06 11:36 UTC, hromau commented on CoffeeHouse.Api/appsettings.json
> +    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=mobilesdb;Trusted_Connection=True;",
change local db to mssql

2022-07-06 11:36 UTC, hromau commented on CoffeeHouse.Api/Program.cs
> +using Microsoft.EntityFrameworkCore;
second time is extra

2022-07-06 11:47 UTC, hromau requested changes

2022-07-06 11:47 UTC, hromau commented on CoffeeHouse.Api/Controllers/CoffeeController.cs
> +        public Coffee Get(int id)
change

2022-07-06 11:55 UTC, stas1408123 requested changes

2022-07-06 11:55 UTC, stas1408123 commented on CoffeeHouse.Api/Controllers/CoffeeController.cs
> +        public void Put(Coffee request)
Rename parametr

2022-07-06 11:55 UTC, stas1408123 commented on CoffeeHouse.Api/Controllers/CoffeeController.cs
> +            request.Cost = 10;
Delete hard code 
You can use swagger for testing

2022-07-06 12:05 UTC, stas1408123 approved these changes

2022-07-06 13:06 UTC, hromau requested changes

2022-07-06 13:06 UTC, hromau commented on CoffeeHouse.Api/Controllers/CoffeeController.cs
> +        public void PostCoffee(Coffee coffee)
rename

2022-07-06 14:31 UTC, hromau requested changes

2022-07-06 14:31 UTC, hromau commented on CoffeeHouse.Api/Controllers/CoffeeController.cs
> +        public void PutCoffee(Coffee coffee)
it shouldn't be PutCofee. let's think about something else

2022-07-06 14:32 UTC, hromau commented on CoffeeHouse.Api/Controllers/CoffeeController.cs
> +        public void PutCoffee(Coffee coffee)
rename all methods. make all is understandable

2022-07-07 10:17 UTC, hromau approved these changes

2022-07-07 10:17 UTC, hromau commented on CoffeeHouse.Api/Program.cs
> +app.MapGet("/", (CoffeeContext db) => db.Coffees.ToList());
what is the strange routing?

2022-07-07 10:31 UTC, merged